{
 "title": "NaPi FCU3308PG",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "buckets", "query": { "query": "buckets()" } },
   {
    "name": "measurements",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurements(bucket: \"${buckets}\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\" or r[\"_field\"] == \"z_multiplier_voltage\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.voltage) / float(v: r.z_multiplier_voltage),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Ampere",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current\" or r[\"_field\"] == \"z_multiplier_current\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.current) /  float(v: r.z_multiplier_current),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Watt",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\" or r[\"_field\"] == \"z_multiplier_power\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.power) /  float(v: r.z_multiplier_power),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\" or r[\"_field\"] == \"z_multiplier_voltage\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.voltage) / float(v: r.z_multiplier_voltage),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Ampere",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current\" or r[\"_field\"] == \"z_multiplier_current\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.current) /  float(v: r.z_multiplier_current),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\" or r[\"_field\"] == \"z_multiplier_power\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.power) /  float(v: r.z_multiplier_power),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "energy1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy1\" or r[\"_field\"] == \"z_multiplier_energy1\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.energy1) /  float(v: r.z_multiplier_energy1),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "PF" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"powerfactor\" or r[\"_field\"] == \"z_multiplier_pf\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.powerfactor) /  float(v: r.z_multiplier_pf),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "description": "50Hz config",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"freq\" or r[\"_field\"] == \"z_multiplier_freq\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: r.freq) /  float(v: r.z_multiplier_freq),\n        _measurement: \"${measurements}\",\n     }))\n  |> keep(columns: [\"_time\",\"_value\",\"_measurement\",\"_field\"])\n  |> yield(name: \"_value\")"
    }
   ]
  }
 ]
}