{
 "title": "donoff-3phase-current",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "buckets", "query": "buckets()" },
   {
    "name": "measurements",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurements(bucket: \"${buckets}\")"
   },
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n    bucket: \"${buckets}\",\r\n    tag: \"host\",\r\n    measurement: \"${measurements}\",\r\n)"
   },
   {
    "name": "dev",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\noption windowPeriod = 1m\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"bucket1\",\r\n  measurement: \"sensors\",\r\n  tag: \"dev\"\r\n)\r\n"
    }
   },
   {
    "name": "dev_current",
    "query": {
     "query": "from(bucket: \"bucket1\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.type == \"current\"\r\n  )\r\n  |> keep(columns: [\"dev\"])\r\n  |> group()\r\n  |> distinct(column: \"dev\")\r\n  |> sort(columns: [\"dev\"])"
    }
   },
   { "name": "dmzk16", "query": "ДМЖК: 3-х фазный вход" },
   { "name": "current_ph1", "query": "${VAR_CURRENT_PH1}" },
   { "name": "current_ph2", "query": "${VAR_CURRENT_PH2}" },
   { "name": "current_ph3", "query": "${VAR_CURRENT_PH3}" },
   { "name": "current_summ", "query": "${VAR_CURRENT_SUMM}" },
   { "name": "project", "query": "donoff" }
  ]
 },
 "panels": [
  {
   "title": "Девайс: ${dev}",
   "type": "stat",
   "description": "Если есть описание что это, пишем в запросе",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -1m)\n  |> filter(fn: (r) =>\n    r.dev == \"${dev_current}\"\n  )\n  |> map(fn: (r) => {\n  d = string(v: r.dev)\n  label =\n    if d == \"dmzk16\" then \"${dmzk16}\"\n    else \"no decr\"\n    \n\n  return { r with dev_label1: d+\"->\"+label }\n})\n|> keep(columns: [\"dev_label1\"])"
    }
   ]
  },
  {
   "title": "SUM of 3ph - sct013x3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\" and\r\n    r._field == \"sct013x3\" \r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"current1\")"
    },
    {}
   ]
  },
  {
   "title": "SUM of 3Phase - I (A) ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"bucket1\")\r\n  |> range(start: -60s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\" and\r\n    r._field == \"${current_summ}\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |>last()"
    }
   ]
  },
  {
   "title": "1 of 3Phase - I (A) ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"bucket1\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\"\r\n  )\r\n  |> filter(fn: (r) => r._field == \"${current_ph1}\")\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |>last()"
    }
   ]
  },
  {
   "title": "2 of 3Phase - I (A) ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"bucket1\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\" and\r\n    r._field == \"${current_ph2}\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |>last()"
    }
   ]
  },
  {
   "title": "3 of 3Phase - I (A) ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"bucket1\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\" and\r\n    r._field == \"${current_ph3}\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |>last()"
    }
   ]
  },
  {
   "title": "Phase1 - I1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\" and\r\n    r._field == \"${current_ph1}\" \r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"current1\")"
    },
    {}
   ]
  },
  {
   "title": "Phase2- I2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\" and\r\n    r._field == \"${current_ph2}\" \r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"current1\")"
    },
    {}
   ]
  },
  {
   "title": "Phase3- I3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sensors\" and\r\n    r.prj == \"${project}\" and\r\n    r.dev == \"${dev_current}\" and\r\n    r._field == \"${current_ph3}\" \r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"current1\")"
    },
    {}
   ]
  }
 ]
}