{
 "title": "donoff-temper-uni-1",
 "tags": [
  "influxdb",
  "IoT"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "buckets", "query": "buckets()" },
   {
    "name": "measurements",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurements(bucket: \"${buckets}\")"
   },
   {
    "name": "dev",
    "label": "dev",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\noption windowPeriod = 1m\n\nschema.measurementTagValues(\n  bucket: \"bucket1\",\n  measurement: \"sensors\",\n  tag: \"dev\"\n)\n"
    }
   },
   {
    "name": "dev_label",
    "query": "dmzk10  : Деревня Розетка 1, dmzk11  : Хозблок, dmzk12  : Теплица"
   },
   { "name": "dmzk10", "query": "ДМЖЕ:Кухня diff" },
   { "name": "dmzk15", "query": "ДМЖК:Кухня кондей" },
   { "name": "dmzk13", "query": "ДМЖК: Туалет двойной" },
   { "name": "h2", "query": "ДМЖК: Станция воды в душе" },
   { "name": "tav1", "query": "Салют: Полив и куб." },
   { "name": "project", "query": "donoff" }
  ]
 },
 "panels": [
  {
   "title": "Device: ${dev}",
   "type": "stat",
   "description": "Если есть описание что это, пишем в запросе",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r.dev == \"${dev}\" and\n    r.prj == \"${project}\"\n  )\n  |> map(fn: (r) => {\n  d = string(v: r.dev)\n  label =\n    if d == \"dmzk10\" then \"${dmzk10}\"\n    else if d == \"h2\" then \"${h2}\"\n    else if d == \"dmzk15\" then \"${dmzk15}\"\n    else if d == \"tav1\" then \"${tav1}\"\n    else if d == \"dmzk13\" then \"${dmzk13}\"\n    else \"no decr\"\n    \n\n  return { r with dev_label1: d+\"->\"+label }\n})\n|> keep(columns: [\"dev_label1\"])"
    }
   ]
  },
  {
   "title": "UP TIME",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"time\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\"\n  )\n  |> filter(fn: (r) => r._field == \"time_up\")\n  |>last()"
    }
   ]
  },
  {
   "title": "temp_out ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"temp_out\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n  //>last()"
    }
   ]
  },
  {
   "title": "temp_in (optional)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"temp_in\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n"
    }
   ]
  },
  {
   "title": "r1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"relays\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" \n   )\n  |> filter(fn: (r) => r._field == \"r1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"corrected_temp\")"
    }
   ]
  },
  {
   "title": "R1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"relays\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\"\n  )\n  |> filter(fn: (r) => r._field == \"r1\")\n  |>last()"
    }
   ]
  },
  {
   "title": "R1 ON time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"time\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\"\n  )\n  |> filter(fn: (r) => r._field == \"time_comm\")\n  |>last()"
    }
   ]
  },
  {
   "title": "R2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"relays\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\"\n  )\n  |> filter(fn: (r) => r._field == \"r2\")\n  |>last()"
    }
   ]
  },
  {
   "title": "Relay1 OFF time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"time\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\"\n  )\n  |> filter(fn: (r) => r._field == \"time_down\")\n  |>last()"
    }
   ]
  },
  {
   "title": "temp_out2  (optional)",
   "type": "gauge",
   "description": "(optional)",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"temp_out2\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n  //|>last()"
    }
   ]
  },
  {
   "title": "temp_odd (optional)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"temp_odd\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n  //|>last()"
    }
   ]
  },
  {
   "title": "r2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"relays\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" \n   )\n  |> filter(fn: (r) => r._field == \"r2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"corrected_temp\")"
    }
   ]
  },
  {
   "title": "Current (optional)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: -30s)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"current\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n  //|>last()"
    }
   ]
  },
  {
   "title": "temp_out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"temp_out\" and\n    r._value != -12800 and\n    r._value != -12700\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"corrected_temp\")"
    }
   ]
  },
  {
   "title": "temp_out2 ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"temp_out2\" and\n    r._value != -12800 and\n    r._value != -12700\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"corrected_temp\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"sensors\" and\n    r.prj == \"${project}\" and\n    r.dev == \"${dev}\" and\n    r._field == \"current\"\n  )\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / float(v: r.mult) }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"current\")"
    }
   ]
  }
 ]
}