{
 "title": "Exagate-SIPH-OUTLETS",
 "time": { "from": "2024-05-31T10:50:39.662Z", "to": "2024-05-31T10:58:43.990Z" },
 "templating": {
  "list": [
   { "name": "buckets", "query": "buckets()" },
   {
    "name": "measurements",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurements(bucket: \"${buckets}\")"
   },
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n    bucket: \"${buckets}\",\r\n    tag: \"host\",\r\n    measurement: \"${measurements}\",\r\n)"
   },
   {
    "name": "device",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n    bucket: \"${buckets}\",\r\n    tag: \"name\",\r\n    measurement: \"${measurements}\",\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "OUTLET_XX Current",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"O1_Current\" or r[\"_field\"]==\"O2_Current\" or r[\"_field\"] == \"O3_Current\" or r[\"_field\"] == \"O4_Current\" or r[\"_field\"] == \"O5_Current\" or r[\"_field\"] == \"O6_Current\" or r[\"_field\"] == \"O7_Current\" or r[\"_field\"] == \"O8_Current\")\r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "OUTLET_XX ApperantPower",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"O1_ApperantPower\" or r[\"_field\"]==\"O2_ApperantPower\" or r[\"_field\"] == \"O3_ApperantPower\" or r[\"_field\"] == \"O4_ApperantPower\" or r[\"_field\"] == \"O5_ApperantPower\" or r[\"_field\"] == \"O6_ApperantPower\" or r[\"_field\"] == \"O7_ApperantPower\" or r[\"_field\"] == \"O8_ApperantPower\")\r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: r._value * 10.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "O_X ApperantPower",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"O1_ApperantPower\" or r[\"_field\"] == \"O2_ApperantPower\" or r[\"_field\"] == \"O3_ApperantPower\" or r[\"_field\"] == \"O4_ApperantPower\")\r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: r._value * 10.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "O_X ApperantPower",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"O5_ApperantPower\" or r[\"_field\"] == \"O6_ApperantPower\" or r[\"_field\"] == \"O7_ApperantPower\" or r[\"_field\"] == \"O8_ApperantPower\")\r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: r._value * 10.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "O_X Energy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"O1_Energy\" or r[\"_field\"] == \"O2_Energy\" or r[\"_field\"] == \"O3_Energy\" or r[\"_field\"] == \"O4_Energy\")\r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "O_X Energy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${buckets}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurements}\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${device}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"O5_Energy\" or r[\"_field\"] == \"O6_Energy\" or r[\"_field\"] == \"O7_Energy\" or r[\"_field\"] == \"O8_Energy\")\r\n  |> toFloat()\r\n  |> map(fn: (r) => ({ r with _value: r._value * 0.001 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}